import Head from "next/head";
import { useState } from "react";
import clientPromise from "../lib/mongoDB";
import Inputs from "../components/Inputs";
import ErrorModal from "../components/errorModal";
import styles from "../styles/Home.module.css";

export default function Home({ dollars }) {
  const [visible, setVisible] = useState(false);

  if (visible === false) {
    return (
      <div>
        <Head>
          <title>Expenses App</title>
          <meta
            name="description"
            content="Simple budgeting and expenses application"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Inputs data={dollars} handleOpen={() => setVisible(true)} />
      </div>
    );
  } else {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ErrorModal handleClose={() => setVisible(false)} isVisible={visible} />
      </div>
    );
  }
}

export async function getServerSideProps() {
  const client = await clientPromise;
  const dollars = await client
    .db("expenses")
    .collection("deposits")
    .find({})
    .toArray();
  return {
    props: { dollars: JSON.parse(JSON.stringify(dollars)) },
  };
}
